# fly.toml app configuration file generated for muddy-dew-4792 on 2023-07-31T05:24:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "muddy-dew-4792"
primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
